# -------------------------------------------------------------------------------------------
# Daniel Peace
# CSUCI / Coordinated Robotics - DTC
# -------------------------------------------------------------------------------------------
# Contains an integer to indicate the current timer that is active
# APRILTAG_COUNTDOWN      = 0
# APRILTAG_TIMER          = 1
# PREDICTION_COUNTDOWN    = 2
# PREDICTION_TIMER        = 3

int32 current_timer