# -------------------------------------------------------------------------------------------
# Daniel Peace
# CSUCI / Coordinated Robotics - DTC
# -------------------------------------------------------------------------------------------
# Used to hold a response from an HTTP status request

float64             clock
string              team
string              user
Remaining_reports   remaining_reports