# -------------------------------------------------------------------------------------------
# Daniel Peace
# CSUCI / Coordinated Robotics - DTC
# -------------------------------------------------------------------------------------------
# Holds information about a timer including the amount of time left and
# the timer's status. "timer_status" should have three values
# 0 means timer is not active (finished)
# 1 means the timer is active (started)
# 2 means the timer was canceled (canceled)

int32 timer_status
int32 time_left