# -------------------------------------------------------------------------------------------
# Daniel Peace
# CSUCI / Coordinated Robotics - DTC
# -------------------------------------------------------------------------------------------
# Contains all information, as outlined by DARPA, for a vitals report

int32   casualty_id
string  team
string  system
string  type
int32   value
int32   time_ago