# -------------------------------------------------------------------------------------------
# Daniel Peace
# CSUCI / Coordinated Robotics - DTC
# -------------------------------------------------------------------------------------------
# Contains all information, as outlined by DARPA, for a vitals report response

string  run
string  team
string  user
string  system
float64 clock
string  report_id
string  report_timestamp
int32   reports_remaining
string  report_status
int32   casualty_id
string  type
int32   value
int32   time_ago